[project]
name = "mlp"
version = "0.1.0"
description = "Machine Learning Practice"
readme = "README.md"
authors = [
    { name = "Rajnish Yadav", email = "yrajnishds@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
mlp = "mlp:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
